qubership-spark-customized: ghcr.io/axcelblaze003/qubership-spark-customized:1.0.3
qubership-spark-on-k8s-transfer: ghcr.io/axcelblaze003/qubership-spark-on-k8s-transfer:1.0.3
qubership-spark-on-k8s-tests: ghcr.io/axcelblaze003/qubership-spark-on-k8s-tests:1.0.3
qubership-spark-operator: ghcr.io/axcelblaze003/qubership-spark-operator:1.0.3
qubership-spark-customized-py: ghcr.io/axcelblaze003/qubership-spark-customized-py:1.0.3
qubership-tests-spark-hive-connection: ghcr.io/axcelblaze003/qubership-tests-spark-hive-connection:1.0.3
qubership-tests-spark-pi-long-run: ghcr.io/axcelblaze003/qubership-tests-spark-pi-long-run:1.0.3
qubership-tests-spark-word-count-s3: ghcr.io/axcelblaze003/qubership-tests-spark-word-count-s3:1.0.3
qubership-tests-spark-streaming-word-count: ghcr.io/axcelblaze003/qubership-tests-spark-streaming-word-count:1.0.3
qubership-tests-spark-streaming-checkpoint: ghcr.io/axcelblaze003/qubership-tests-spark-streaming-checkpoint:1.0.3
qubership-deployment-status-provisioner: ghcr.io/axcelblaze003/qubership-deployment-status-provisioner:0.1.4
oauth2_proxy_release-image: quay.io/oauth2-proxy/oauth2-proxy:v7.8.1